/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import java.util.Scanner;
import javax.swing.JOptionPane;
import main.Shop;
import model.Amount;
import model.Product;

/**
 *
 * @author nilar
 */
public class ProductView extends javax.swing.JDialog {

    private int opcion;
    private Shop shop;

    /**
     * Creates new form ProductView
     */
    public ProductView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    ProductView(Shop tienda, int option) {
        initComponents();
        opcion = option;
        shop = tienda;
        switch (opcion) {
            case 2:
                jLPrice.setVisible(false);
                jTPrice.setVisible(false);
                break;
            case 9:
                jLPrice.setVisible(false);
                jTPrice.setVisible(false);
                jLStock.setVisible(false);
                jTStock.setVisible(false);
                break;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLName = new javax.swing.JLabel();
        jLStock = new javax.swing.JLabel();
        jLPrice = new javax.swing.JLabel();
        jTName = new javax.swing.JTextField();
        jTStock = new javax.swing.JTextField();
        jTPrice = new javax.swing.JTextField();
        jBOk = new javax.swing.JButton();
        jBCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLName.setText("Nombre del producto.");

        jLStock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLStock.setText("Stock producto:");

        jLPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLPrice.setText("Precio producto:");

        jTName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNameActionPerformed(evt);
            }
        });

        jBOk.setText("Ok");
        jBOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOkActionPerformed(evt);
            }
        });

        jBCancel.setText("Cancelar");
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLName)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLStock, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLPrice, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(35, 35, 35)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTStock, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jBOk, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLName)
                    .addComponent(jTName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStock)
                    .addComponent(jTStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBOk)
                    .addComponent(jBCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNameActionPerformed

    private void jBOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOkActionPerformed
        switch (opcion) {
            case 1:
                addProductView();
                break;
            case 2:
                addStockView();
                break;
            case 9:
                deleteProductView();
                break;

        }
    }//GEN-LAST:event_jBOkActionPerformed

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBCancelActionPerformed

    public void addProductView() {
        if (shop.isInventoryFull()) {
            JOptionPane.showMessageDialog(this, "El inventario esta lleno", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String name = jTName.getText();

        boolean product = shop.productExists(name);

        if (!product) {
            double wholesalerPrice = parseDouble(jTPrice.getText());
            int stock = parseInt(jTStock.getText());
            shop.inventory.add(new Product(name, new Amount(wholesalerPrice, "€"), stock));
            shop.numberProducts++;
            JOptionPane.showMessageDialog(this, "El producto se a añadido correctamnete en el inventario", "SUCCES", JOptionPane.PLAIN_MESSAGE);

            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "El producto a añadir ya existe en el inventario.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }

    public void addStockView() {
        String name = jTName.getText();
        Product product = shop.findProduct(name);

        if (product != null) {
            int stock = parseInt(jTStock.getText());
            int newStock = product.getStock() + stock;
            product.setStock(newStock);
            JOptionPane.showMessageDialog(this, "El stock del producto " + name + " ha sido actualizado ", "SUCCES", JOptionPane.PLAIN_MESSAGE);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "No se ha encontrado el producto." + name, "ERROR", JOptionPane.ERROR_MESSAGE);

        }
    }

    public void deleteProductView() {
        String name = jTName.getText();
        boolean product = shop.productExists(name);

        if (product) {
            Product prod = shop.findProduct(name);
            if (prod != null) {
                for (int i = 0; i < shop.inventory.size(); i++) {
                    if (shop.inventory.get(i) != null && shop.inventory.get(i).getName().equalsIgnoreCase(name)) {
                        shop.inventory.remove(i);
                        JOptionPane.showMessageDialog(this, "El stock del producto " + name + " ha sido eliminado ", "SUCCES", JOptionPane.PLAIN_MESSAGE);
                        dispose();
                    }
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "El producto a eliminar no existe en el inventario", "ERROR", JOptionPane.ERROR_MESSAGE);
               dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBOk;
    private javax.swing.JLabel jLName;
    private javax.swing.JLabel jLPrice;
    private javax.swing.JLabel jLStock;
    private javax.swing.JTextField jTName;
    private javax.swing.JTextField jTPrice;
    private javax.swing.JTextField jTStock;
    // End of variables declaration//GEN-END:variables
}
